sonar.cpd.exclusions=
  src/modules/content/data/tips.mock.ts,
  **/tailwind.config.js,
  src/types/supabase/supabase.ts,
  src/components/**/__tests__/**,
  src/**/__tests__/**,
  **/*.test.ts,
  **/*.test.tsx,
  **/*.spec.ts,
  **/*.spec.tsx,
  **/*.hook.test.tsx
sonar.duplications.exclusions=
  **/__tests__/**,
  **/*.test.ts,
  **/*.test.tsx,
  **/*.spec.ts,
  **/*.spec.tsx,
  **/*.hook.test.tsx,
  src/types/supabase/supabase.ts
sonar.exclusions=
  supabase/migrations/**,
  supabase/tests/**,
  **/__tests__/**,
  **/*.test.ts,
  **/*.test.tsx,
  **/*.spec.ts,
  **/*.spec.tsx,
  **/*.hook.test.tsx
