export enum PagesUrls {
  LOGIN = '/authentication/login',
  HOME = '/home',
  REVIEW = '/review',
  ADDREES_DETAILS = '/address',
  REVIEW_DETAILS = '/review/details/:id',
  REVIEW_CREATE = '/review/create',
  ABOUT = '/about',
  CONTACT = '/contact',
  FAQ = '/faq',
  TIPS = '/tips',
  TIPS_DETAILS = '/tips/:id',
  PROFILE = '/profile',
  EDIT_REVIEW = '/review/edit',
  GOOD_PRACTICES = '/good-practices',
  PRIVACY_POLICY = '/privacidad',
  TERMS_AND_CONDITIONS = '/terminos',
  REAL_ESTATE = '/real-estate/',
  REAL_ESTATE_VIEW = '/real-estate/:id',
  REAL_ESTATE_CREATE = '/real-estate/create',
  REAL_ESTATE_CREATE_REVIEW = '/real-estate/:id/review/create',
  REAL_ESTATE_UPDATE_REVIEW = '/real-estate/:id/review/:reviewId/update',
  REAL_ESTATE_VIEW_REVIEW = '/real-estate/:id/review/:reviewId/view',
  REAL_ESTATE_UPDATE = '/real-estate/[id]/update',
}
